trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- script: yarn
  displayName: 'Install'

- script: npm run build
  displayName: 'Build'

- script: npm test
  displayName: 'Test'

- script: npm run lint
  displayName: 'Lint'

- script: NODE_ENV=test ./node_modules/.bin/nyc npm test && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
  displayName: 'Public coverage'
