trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- script: yarn
  displayName: 'Install'

- script: npm run build
  displayName: 'Build'

- script: npm test
  displayName: 'Test'

- script: npm run lint
  displayName: 'Lint'

- script: ./node_modules/.bin/nyc report --reporter=cobertura
  displayName: 'Coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
  displayName: 'Publish coverage'

- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
  displayName: 'Check build quality'
  inputs:
    checkCoverage: true
    coverageType: lines
    coverageThreshold: 100
