name: CI

on: [push]

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Lint, test and verify coverage
      run: |
        npm run lint
        npm run coverage

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com'
    - name: Install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

