name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com'
    - name: Install and build
      run: |
        npm ci
        npm run build
      env:
        CI: true
    - name: Lint, test and verify coverage
      run: |
        npm run lint
        npm run coverage
    - name: Publish to npm
      run: |
        # Try to publish and ignore any errors (it was already published)
        npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
